enum ActionTypes {
  PLAYER_SET_SONG = 'PLAYER-SET-SONG',
  PLAYER_SET_NEXT_SONG = 'PLAYER-SET-NEXT-SONG',
  PLAYER_SET_COLOR_PALETTE = 'PLAYER_SET_COLOR_PALETTE',
  PLAYER_SET_QUEUE = 'PLAYER_SET_QUEUE',
  PLAYER_SET_PLAY = 'PLAYER_SET_PLAY',
  PLAYER_SET_PAUSE = 'PLAYER_SET_PAUSE',
  PLAYER_NEXT = 'PLAYER_NEXT',
  PLAYER_PREV = 'PLAYER_PREV',
  PLAYER_SET_VOLUME = 'PLAYER_SET_VOLUME',
  PLAYER_SET_LOADING = 'PLAYER_SET_LOADING',
  PLAYER_SET_LOADING_DONE = 'PLAYER_SET_LOADING_DONE',
  PLAYER_NEXT_INDEX = 'PLAYER_NEXT_INDEX',
  PLAYER_PREV_INDEX = 'PLAYER_PREV_INDEX',
  PLAYER_SET_INDEX = 'PLAYER_SET_INDEX',
  PLAYER_SET_TIME = 'PLAYER_SET_TIME',

  SETTINGS_SET = 'SETTINGS_SET',
  SETTINGS_TOGGLE_CONTROLS = 'SETTINGS_TOGGLE_CONTROLS',
}

export default ActionTypes;
