enum ActionTypes {
  PLAYER_SET_SONG = 'PLAYER-SET-SONG',
  PLAYER_SET_COLOR_PALETTE = 'PLAYER_SET_COLOR_PALETTE',
  SETTINGS_SET_MUSIC_DIR = 'SETTINGS_SET_MUSIC_DIR',
  SETTINGS_SET = 'SETTINGS_SET',
}

export default ActionTypes;
